In [1]:
import pandas as pd
from sqlalchemy import create_engine, text

In [2]:
Database_url = "postgresql://neondb_owner:npg_qStXmZLBQ5A9@ep-wispy-sunset-axezqxvm-pooler.c-4.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require"

engine = create_engine(Database_url)

In [3]:
#### Create the connection
engine = create_engine(
    Database_url,
    poolclass= None,
    connect_args={
        "sslmode": "require",
        "connect_timeout": 10
    }
)

###### test the connection
try: 
    with engine.connect() as connection:
        result = connection.execute(text("SELECT 1"))
        print("Database response:", result.fetchone())
        print("Successful connection")

except Exception as e:
    print("Coonnection failed:", repr(e))

Database response: (1,)
Successful connection

In [4]:
query = """ 
SELECT table_name
FROM information_schema.tables
WHERE table_schema = 'public';
"""

table = pd.read_sql(query, engine)
table.head()

       table_name
0        bookings
1          guests
2          hotels
3         reviews
4  clean_bookings

# Load the bookings data

In [5]:
booking = pd.read_sql(
    "SELECT * FROM bookings", engine
)

booking.head()

,booking_id,guest_id,hotel_id,room_type,booking_channel,check_in_date,check_out_date,total_amount,stay_duration
0,1,6699,18,Suite,Direct Website,2025-05-25,2025-05-26,296.44,1
1,2,11380,23,Deluxe,Corporate Portal,2025-01-09,2025-01-13,483.56,4
2,3,4812,13,Executive,Travel Agent,2025-03-04,2025-03-06,415.59,2
3,4,982,12,Family Room,Airbnb,2026-03-06,2026-03-09,601.18,3
4,5,615,5,Deluxe,Expedia,2025-02-25,2025-03-02,603.85,5

In [6]:
### Load the guests data
guests = pd.read_sql(
    "SELECT * FROM  guests", engine
)

guests.head()

   guest_id customer_type loyalty_status               country  previous_stays
0         1       Leisure            NaN             Australia               0
1         2       Leisure            NaN               Germany               1
2         3      Business           Gold        United Kingdom               0
3         4        Family         Silver  United Arab Emirates               8
4         5     Corporate            NaN                France               0

In [7]:
guests.info()

<class 'pandas.DataFrame'>
RangeIndex: 12000 entries, 0 to 11999
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   guest_id        12000 non-null  int64
 1   customer_type   12000 non-null  str
 2   loyalty_status  5964 non-null   str
 3   country         12000 non-null  str
 4   previous_stays  12000 non-null  int64
dtypes: int64(2), str(3)
memory usage: 468.9 KB

In [8]:
booking.info()

<class 'pandas.DataFrame'>
RangeIndex: 35000 entries, 0 to 34999
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   booking_id       35000 non-null  int64
 1   guest_id         35000 non-null  int64
 2   hotel_id         35000 non-null  int64
 3   room_type        35000 non-null  str
 4   booking_channel  35000 non-null  str
 5   check_in_date    35000 non-null  str
 6   check_out_date   35000 non-null  str
 7   total_amount     35000 non-null  float64
 8   stay_duration    35000 non-null  int64
dtypes: float64(1), int64(4), str(4)
memory usage: 2.4 MB

In [9]:
hotel = pd.read_sql(
    "SELECT * FROM hotels", engine
)

hotel.head()

   hotel_id            hotel_name    location  star_rating  total_rooms
0         1  The Birmingham Grand  Birmingham            4          254
1         2   The London Heritage      London            5          234
2         3   The Oxford Boutique      Oxford            3          146
3         4  The Glasgow Heritage     Glasgow            3           84
4         5  Glasgow Metropolitan     Glasgow            4          214

In [10]:
review = pd.read_sql(
    "SELECT * FROM reviews", engine
)

review.head()

,review_id,booking_id,guest_id,hotel_id,review_text,rating_score,review_date,sentiment_label
0,1,1,6699,18,The overall price was fair for what we paid. M...,3.2,2025-06-02,neutral
1,2,2,11380,23,The room was nothing out of the ordinary for w...,4.0,2025-01-22,positive
2,3,3,4812,13,"Unfortunately, the pool was outdated — it clea...",1.9,2025-03-13,negative
3,4,4,982,12,We were disappointed that the neighborhood was...,2.2,2026-03-18,negative
4,5,5,615,5,The room service was standard hotel fare for w...,3.3,2025-03-03,neutral

In [11]:
review.info()

<class 'pandas.DataFrame'>
RangeIndex: 35000 entries, 0 to 34999
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   review_id        35000 non-null  int64
 1   booking_id       35000 non-null  int64
 2   guest_id         35000 non-null  int64
 3   hotel_id         35000 non-null  int64
 4   review_text      35000 non-null  str
 5   rating_score     35000 non-null  float64
 6   review_date      35000 non-null  str
 7   sentiment_label  35000 non-null  str
dtypes: float64(1), int64(4), str(3)
memory usage: 2.1 MB

### Exploratory Data Analysis

In [12]:
import plotly.express as px
import plotly.graph_objects as go
import plotly.subplots 
from plotly.subplots import make_subplots

In [13]:
## Total conunts of room_type
room_type = booking['room_type'].value_counts().reset_index()
room_type

### Revenue by room type
room_revenue = booking.groupby('room_type')['total_amount'].sum().reset_index()
room_revenue

### Booking channels
channels = booking['booking_channel'].value_counts().reset_index()
channels

### Revenue generated by booking channel
channel_revenue = booking.groupby('booking_channel')['total_amount'].sum().reset_index()
channel_revenue

    booking_channel  total_amount
0            Airbnb    1604609.36
1       Booking.com    3654237.93
2  Corporate Portal    1611396.00
3    Direct Website    4051385.20
4           Expedia    2452361.55
5      Travel Agent    1618571.44
6           Walk-in    1319438.23

In [14]:
stay= booking['stay_duration'].value_counts().reset_index()
stay

   stay_duration  count
0              2  10425
1              3   8679
2              1   5299
3              4   5243
4              5   3614
5              7   1740

In [15]:
# create subplot
fig = make_subplots(
    rows = 3, cols = 2,
    subplot_titles=("Total Room Distribution", "Revenue Generated by Room Type", "Booking Channel Distribution", "Revenue Generated by Booking Channel", "Stay Duration Distribution")
)
##Add charts
fig.add_trace(go.Bar(x= room_type['room_type'], y = room_type['count'], name ='Count', marker_color = 'teal'), row = 1, col = 1)
fig.add_trace(go.Bar(x =room_revenue['room_type'], y = room_revenue['total_amount'], name= 'Revenue', marker_color = 'indianred'), row = 1, col = 2)
fig.add_trace(go.Bar(x = channels['booking_channel'], y = channels['count'], name = 'Count', marker_color = 'blue'), row = 2, col = 1)
fig.add_trace(go.Bar(x = channel_revenue['booking_channel'], y = channel_revenue['total_amount'], name = 'Revenue', marker_color = 'yellow'), row= 2, col =2)
fig.add_trace(go.Bar(x = stay['stay_duration'], y= stay['count'], name ='Count', marker_color = 'goldenrod'), row = 3, col =1)

fig.update_layout(height = 800, title_text = "Booking Analysis Overview", showlegend = False)

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'marker': {'color': 'teal'},
              'name': 'Count',
              'type': 'bar',
              'x': array(['Standard', 'Deluxe', 'Executive', 'Family Room', 'Suite', 'Twin'],
                         dtype=object),
              'xaxis': 'x',
              'y': {'bdata': 'ZCmrIa0UKRDYDfsK', 'dtype': 'i2'},
              'yaxis': 'y'},
             {'marker': {'color': 'indianred'},
              'name': 'Revenue',
              'type': 'bar',
              'x': array(['Deluxe', 'Executive', 'Family Room', 'Standard', 'Suite', 'Twin'],
                         dtype=object),
              'xaxis': 'x2',
              'y': {'bdata': 'SOF6VNYMTkGF61F4U4BIQfYoXE90d0BBKVyPYqq/R0EfheuRLB1HQY/C9SirRypB', 'dtype': 'f8'},
              'yaxis': 'y2'},
             {'marker': {'color': 'blue'},
              'name': 'Count',
              'type': 'bar',
              'x': array(['Direct Website', 'Booking.com', 'Expedia', 'Travel Agent', 'Airbnb',
                          'Corporate Portal', 'Walk-in'], dtype=object),
              'xaxis': 'x3',
              'y': {'bdata': '8CGAHpkUyQ1YDVMNOws=', 'dtype': 'i2'},
              'yaxis': 'y3'},
             {'marker': {'color': 'yellow'},
              'name': 'Revenue',
              'type': 'bar',
              'x': array(['Airbnb', 'Booking.com', 'Corporate Portal', 'Direct Website',
                          'Expedia', 'Travel Agent', 'Walk-in'], dtype=object),
              'xaxis': 'x4',
              'y': {'bdata': 'w/UoXAF8OEFxPQr3LuFLQQAAAACEljhBmpmZmdzoTkFmZmbGxLVCQQrXo3CLsjhBrkfhOg4iNEE=',
                    'dtype': 'f8'},
              'yaxis': 'y4'},
             {'marker': {'color': 'goldenrod'},
              'name': 'Count',
              'type': 'bar',
              'x': {'bdata': 'AgMBBAUH', 'dtype': 'i1'},
              'xaxis': 'x5',
              'y': {'bdata': 'uSjnIbMUexQeDswG', 'dtype': 'i2'},
              'yaxis': 'y5'}],
    'layout': {'annotations': [{'font': {'size': 16},
                                'showarrow': False,
                                'text': 'Total Room Distribution',
                                'x': 0.225,
                                'xanchor': 'center',
                                'xref': 'paper',
                                'y': 1.0,
                                'yanchor': 'bottom',
                                'yref': 'paper'},
                               {'font': {'size': 16},
                                'showarrow': False,
                                'text': 'Revenue Generated by Room Type',
                                'x': 0.775,
                                'xanchor': 'center',
                                'xref': 'paper',
                                'y': 1.0,
                                'yanchor': 'bottom',
                                'yref': 'paper'},
                               {'font': {'size': 16},
                                'showarrow': False,
                                'text': 'Booking Channel Distribution',
                                'x': 0.225,
                                'xanchor': 'center',
                                'xref': 'paper',
                                'y': 0.6111111111111112,
                                'yanchor': 'bottom',
                                'yref': 'paper'},
                               {'font': {'size': 16},
                                'showarrow': False,
                                'text': 'Revenue Generated by Booking Channel',
                                'x': 0.775,
                                'xanchor': 'center',
                                'xref': 'paper',
                                'y': 0.6111111111111112,
                                'yanchor': 'bottom',
                                'yref': 'paper'},
                               {'font': {'size': 16},
                                'showarrow': False,
                                'text': 'Stay Duration Distribution',
                                'x': 0.225,
                                'xanchor': 'center',
                                'xref': 'paper',
                                'y': 0.22222222222222224,
                                'yanchor': 'bottom',
                                'yref': 'paper'}],
               'height': 800,
               'showlegend': False,
               'template': '...',
               'title': {'text': 'Booking Analysis Overview'},
               'xaxis': {'anchor': 'y', 'domain': [0.0, 0.45]},
               'xaxis2': {'anchor': 'y2', 'domain': [0.55, 1.0]},
               'xaxis3': {'anchor': 'y3', 'domain': [0.0, 0.45]},
               'xaxis4': {'anchor': 'y4', 'domain': [0.55, 1.0]},
               'xaxis5': {'anchor': 'y5', 'domain': [0.0, 0.45]},
               'xaxis6': {'anchor': 'y6', 'domain': [0.55, 1.0]},
               'yaxis': {'anchor': 'x', 'domain': [0.7777777777777778, 1.0]},
               'yaxis2': {'anchor': 'x2', 'domain': [0.7777777777777778, 1.0]},
               'yaxis3': {'anchor': 'x3', 'domain': [0.3888888888888889, 0.6111111111111112]},
               'yaxis4': {'anchor': 'x4', 'domain': [0.3888888888888889, 0.6111111111111112]},
               'yaxis5': {'anchor': 'x5', 'domain': [0.0, 0.22222222222222224]},
               'yaxis6': {'anchor': 'x6', 'domain': [0.0, 0.22222222222222224]}}
})

In [16]:
booking.info()

<class 'pandas.DataFrame'>
RangeIndex: 35000 entries, 0 to 34999
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   booking_id       35000 non-null  int64
 1   guest_id         35000 non-null  int64
 2   hotel_id         35000 non-null  int64
 3   room_type        35000 non-null  str
 4   booking_channel  35000 non-null  str
 5   check_in_date    35000 non-null  str
 6   check_out_date   35000 non-null  str
 7   total_amount     35000 non-null  float64
 8   stay_duration    35000 non-null  int64
dtypes: float64(1), int64(4), str(4)
memory usage: 2.4 MB

In [17]:
review.info()

<class 'pandas.DataFrame'>
RangeIndex: 35000 entries, 0 to 34999
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   review_id        35000 non-null  int64
 1   booking_id       35000 non-null  int64
 2   guest_id         35000 non-null  int64
 3   hotel_id         35000 non-null  int64
 4   review_text      35000 non-null  str
 5   rating_score     35000 non-null  float64
 6   review_date      35000 non-null  str
 7   sentiment_label  35000 non-null  str
dtypes: float64(1), int64(4), str(3)
memory usage: 2.1 MB

In [18]:
guests.info()

<class 'pandas.DataFrame'>
RangeIndex: 12000 entries, 0 to 11999
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   guest_id        12000 non-null  int64
 1   customer_type   12000 non-null  str
 2   loyalty_status  5964 non-null   str
 3   country         12000 non-null  str
 4   previous_stays  12000 non-null  int64
dtypes: int64(2), str(3)
memory usage: 468.9 KB

In [19]:
hotel.info()

<class 'pandas.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   hotel_id     25 non-null     int64
 1   hotel_name   25 non-null     str
 2   location     25 non-null     str
 3   star_rating  25 non-null     int64
 4   total_rooms  25 non-null     int64
dtypes: int64(3), str(2)
memory usage: 1.1 KB

In [20]:
merge =review.merge(booking, on = ['booking_id', 'guest_id', 'hotel_id'], how = "inner")
merge = merge.merge(guests, on = 'guest_id', how = 'inner')
merge = merge.merge(hotel, on = 'hotel_id', how = "inner")

In [21]:
merge.head()

,review_id,booking_id,guest_id,hotel_id,review_text,rating_score,review_date,sentiment_label,room_type,booking_channel,...,total_amount,stay_duration,customer_type,loyalty_status,country,previous_stays,hotel_name,location,star_rating,total_rooms
0,1,1,6699,18,The overall price was fair for what we paid. M...,3.2,2025-06-02,neutral,Suite,Direct Website,...,296.44,1,Leisure,NaN,France,4,The Aberdeen Grand,Aberdeen,4,118
1,2,2,11380,23,The room was nothing out of the ordinary for w...,4.0,2025-01-22,positive,Deluxe,Corporate Portal,...,483.56,4,Business,Gold,Germany,4,Nottingham Park Hotel,Nottingham,4,95
2,3,3,4812,13,"Unfortunately, the pool was outdated — it clea...",1.9,2025-03-13,negative,Executive,Travel Agent,...,415.59,2,Business,NaN,Ireland,4,The London Boutique,London,4,231
3,4,4,982,12,We were disappointed that the neighborhood was...,2.2,2026-03-18,negative,Family Room,Airbnb,...,601.18,3,Leisure,NaN,Nigeria,0,Manchester Metropolitan,Manchester,3,101
4,5,5,615,5,The room service was standard hotel fare for w...,3.3,2025-03-03,neutral,Deluxe,Expedia,...,603.85,5,Group,NaN,United States,9,Glasgow Metropolitan,Glasgow,4,214

In [22]:
merge.isna().sum()

review_id              0
booking_id             0
guest_id               0
hotel_id               0
review_text            0
rating_score           0
review_date            0
sentiment_label        0
room_type              0
booking_channel        0
check_in_date          0
check_out_date         0
total_amount           0
stay_duration          0
customer_type          0
loyalty_status     17615
country                0
previous_stays         0
hotel_name             0
location               0
star_rating            0
total_rooms            0
dtype: int64

#### Saved the merge dataset

In [23]:
merge.to_csv("../data/processed/merged_raw.csv", index = False)
print("Shape:", merge.shape)

Shape: (35000, 22)